/*
 * API Migraciones
 *
 * API para el proyecto de migraciones de movistar a tigo o claro
 *
 * OpenAPI spec version: 1.0.0
 * Contact: juand.blandont@gmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace ProyectoMigracionMovistarApi.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class AuditoriaItem : IEquatable<AuditoriaItem>
    { 
        /// <summary>
        /// Tipo de evento
        /// </summary>
        /// <value>Tipo de evento</value>

        [DataMember(Name="tipoEvento")]
        public string TipoEvento { get; set; }

        /// <summary>
        /// Descripción de evento
        /// </summary>
        /// <value>Descripción de evento</value>

        [DataMember(Name="descripcion")]
        public string Descripcion { get; set; }

        /// <summary>
        /// Fecha de evento
        /// </summary>
        /// <value>Fecha de evento</value>

        [DataMember(Name="fechaRegistro")]
        public DateTime? FechaRegistro { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class AuditoriaItem {\n");
            sb.Append("  TipoEvento: ").Append(TipoEvento).Append("\n");
            sb.Append("  Descripcion: ").Append(Descripcion).Append("\n");
            sb.Append("  FechaRegistro: ").Append(FechaRegistro).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((AuditoriaItem)obj);
        }

        /// <summary>
        /// Returns true if AuditoriaItem instances are equal
        /// </summary>
        /// <param name="other">Instance of AuditoriaItem to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(AuditoriaItem other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    TipoEvento == other.TipoEvento ||
                    TipoEvento != null &&
                    TipoEvento.Equals(other.TipoEvento)
                ) && 
                (
                    Descripcion == other.Descripcion ||
                    Descripcion != null &&
                    Descripcion.Equals(other.Descripcion)
                ) && 
                (
                    FechaRegistro == other.FechaRegistro ||
                    FechaRegistro != null &&
                    FechaRegistro.Equals(other.FechaRegistro)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (TipoEvento != null)
                    hashCode = hashCode * 59 + TipoEvento.GetHashCode();
                    if (Descripcion != null)
                    hashCode = hashCode * 59 + Descripcion.GetHashCode();
                    if (FechaRegistro != null)
                    hashCode = hashCode * 59 + FechaRegistro.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(AuditoriaItem left, AuditoriaItem right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(AuditoriaItem left, AuditoriaItem right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
