/*
 * API Migraciones
 *
 * API para el proyecto de migraciones de movistar a tigo o claro
 *
 * OpenAPI spec version: 1.0.0
 * Contact: juand.blandont@gmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace ProyectoMigracionMovistarApi.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class DatosAutenticacion : IEquatable<DatosAutenticacion>
    { 
        /// <summary>
        /// Cédula del usuario
        /// </summary>
        /// <value>Cédula del usuario</value>

        [DataMember(Name="usuario")]
        public string Usuario { get; set; }

        /// <summary>
        /// Clave del usuario
        /// </summary>
        /// <value>Clave del usuario</value>

        [DataMember(Name="clave")]
        public string Clave { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class DatosAutenticacion {\n");
            sb.Append("  Usuario: ").Append(Usuario).Append("\n");
            sb.Append("  Clave: ").Append(Clave).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((DatosAutenticacion)obj);
        }

        /// <summary>
        /// Returns true if DatosAutenticacion instances are equal
        /// </summary>
        /// <param name="other">Instance of DatosAutenticacion to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(DatosAutenticacion other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    Usuario == other.Usuario ||
                    Usuario != null &&
                    Usuario.Equals(other.Usuario)
                ) && 
                (
                    Clave == other.Clave ||
                    Clave != null &&
                    Clave.Equals(other.Clave)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (Usuario != null)
                    hashCode = hashCode * 59 + Usuario.GetHashCode();
                    if (Clave != null)
                    hashCode = hashCode * 59 + Clave.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(DatosAutenticacion left, DatosAutenticacion right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(DatosAutenticacion left, DatosAutenticacion right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
