/*
 * API Migraciones
 *
 * API para el proyecto de migraciones de movistar a tigo o claro
 *
 * OpenAPI spec version: 1.0.0
 * Contact: juand.blandont@gmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace ProyectoMigracionMovistarApi.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class MensajeErrorItem : IEquatable<MensajeErrorItem>
    { 
        /// <summary>
        /// Código de error
        /// </summary>
        /// <value>Código de error</value>

        [DataMember(Name="codigoError")]
        public string CodigoError { get; set; }

        /// <summary>
        /// Mensaje de error
        /// </summary>
        /// <value>Mensaje de error</value>

        [DataMember(Name="mensajeError")]
        public string MensajeError { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class MensajeErrorItem {\n");
            sb.Append("  CodigoError: ").Append(CodigoError).Append("\n");
            sb.Append("  MensajeError: ").Append(MensajeError).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((MensajeErrorItem)obj);
        }

        /// <summary>
        /// Returns true if MensajeErrorItem instances are equal
        /// </summary>
        /// <param name="other">Instance of MensajeErrorItem to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(MensajeErrorItem other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    CodigoError == other.CodigoError ||
                    CodigoError != null &&
                    CodigoError.Equals(other.CodigoError)
                ) && 
                (
                    MensajeError == other.MensajeError ||
                    MensajeError != null &&
                    MensajeError.Equals(other.MensajeError)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (CodigoError != null)
                    hashCode = hashCode * 59 + CodigoError.GetHashCode();
                    if (MensajeError != null)
                    hashCode = hashCode * 59 + MensajeError.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(MensajeErrorItem left, MensajeErrorItem right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(MensajeErrorItem left, MensajeErrorItem right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
