/*
 * API Migraciones
 *
 * API para el proyecto de migraciones de movistar a tigo o claro
 *
 * OpenAPI spec version: 1.0.0
 * Contact: juand.blandont@gmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace ProyectoMigracionMovistarApi.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class RespuestaTransaccion : IEquatable<RespuestaTransaccion>
    { 
        /// <summary>
        /// Url de la solicitud
        /// </summary>
        /// <value>Url de la solicitud</value>

        [DataMember(Name="url")]
        public string Url { get; set; }

        /// <summary>
        /// Número del registro
        /// </summary>
        /// <value>Número del registro</value>

        [DataMember(Name="numeroRegistro")]
        public long? NumeroRegistro { get; set; }

        /// <summary>
        /// Notas
        /// </summary>
        /// <value>Notas</value>

        [DataMember(Name="notas")]
        public string Notas { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class RespuestaTransaccion {\n");
            sb.Append("  Url: ").Append(Url).Append("\n");
            sb.Append("  NumeroRegistro: ").Append(NumeroRegistro).Append("\n");
            sb.Append("  Notas: ").Append(Notas).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((RespuestaTransaccion)obj);
        }

        /// <summary>
        /// Returns true if RespuestaTransaccion instances are equal
        /// </summary>
        /// <param name="other">Instance of RespuestaTransaccion to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(RespuestaTransaccion other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    Url == other.Url ||
                    Url != null &&
                    Url.Equals(other.Url)
                ) && 
                (
                    NumeroRegistro == other.NumeroRegistro ||
                    NumeroRegistro != null &&
                    NumeroRegistro.Equals(other.NumeroRegistro)
                ) && 
                (
                    Notas == other.Notas ||
                    Notas != null &&
                    Notas.Equals(other.Notas)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (Url != null)
                    hashCode = hashCode * 59 + Url.GetHashCode();
                    if (NumeroRegistro != null)
                    hashCode = hashCode * 59 + NumeroRegistro.GetHashCode();
                    if (Notas != null)
                    hashCode = hashCode * 59 + Notas.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(RespuestaTransaccion left, RespuestaTransaccion right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(RespuestaTransaccion left, RespuestaTransaccion right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
