/*
 * API Migraciones
 *
 * API para el proyecto de migraciones de movistar a tigo o claro
 *
 * OpenAPI spec version: 1.0.0
 * Contact: juand.blandont@gmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Http.Extensions;
using Microsoft.AspNetCore.Mvc;
using ProyectoMigracionMovistarApi.Attributes;
using ProyectoMigracionMovistarApi.Bussines;
using ProyectoMigracionMovistarApi.Entities;
using ProyectoMigracionMovistarApi.Models;
using ProyectoMigracionMovistarApi.Utils;
using Swashbuckle.AspNetCore.Annotations;
using System.ComponentModel.DataAnnotations;
using System.Threading.Tasks;

namespace ProyectoMigracionMovistarApi.Controllers
{
    /// <summary>
    /// 
    /// </summary>
    [ApiController]
    public class ProcesoApi : APIUtil
    {
        private readonly MigracionDbContext _context;
        private readonly IServiceProvider _serviceProvider;
        public ProcesoApi(MigracionDbContext context, IServiceProvider serviceProvider)
        {
            _context = context;
            _serviceProvider = serviceProvider;
        }

        /// <summary>
        /// Obtiene el listado de procesos de migración
        /// </summary>
        /// <remarks>Retorna todos los procesos de migración realizados, con su estado y métricas. </remarks>
        /// <response code="200">Lista de procesos</response>
        /// <response code="400">Error al recuperar la información</response>
        [HttpGet]
        [Route("migraciones/procesos")]
        [ValidateModelState]
        [SwaggerOperation("ObtenerProcesosMigracion")]
        [SwaggerResponse(statusCode: 200, type: typeof(List<ProcesoResumen>), description: "Lista de procesos")]
        [SwaggerResponse(statusCode: 400, type: typeof(MensajeErrorItem), description: "Error al recuperar la información")]
        public virtual IActionResult ObtenerProcesosMigracion()
        {
            try
            {
                ProcesoBL reglasNegocio = new ProcesoBL(_context);
                List<ProcesoResumen> respuesta = reglasNegocio.ObtenerProcesosMigracion();
                return new ObjectResult(respuesta);
            }
            catch (Exception ex)
            {
                return BadRequest(AdministrarExcepcion(ex));
            }
        }

        /// <summary>
        /// Genera una migración manual
        /// </summary>
        /// <remarks>Genera una migración manual ya sea por parte de un cliente o de un administrador </remarks>
        /// <param name="usuario">Identificación del usuario que llama la función</param>
        /// <param name="body">Datos para la migración</param>
        /// <response code="200">Respuesta del proceso</response>
        /// <response code="400">Inconsistencia de la petición</response>
        [HttpPost]
        [Route("migraciones/{usuario}/manual")]
        [ValidateModelState]
        [SwaggerOperation("RealizarMigracionManual")]
        [SwaggerResponse(statusCode: 200, type: typeof(RespuestaTransaccion), description: "Respuesta del proceso")]
        [SwaggerResponse(statusCode: 400, type: typeof(MensajeErrorItem), description: "Inconsistencia de la petición")]
        public virtual IActionResult RealizarMigracionManual([FromRoute][Required] string usuario, [FromBody] DatosMigracionManual body)
        {
            try
            {
                ProcesoBL reglasNegocio = new ProcesoBL(_context);
                RespuestaTransaccion respuesta = reglasNegocio.RealizarMigracionManual(usuario, body);
                respuesta.Url = new Uri(Request.GetDisplayUrl()).ToString();
                return new ObjectResult(respuesta);
            }
            catch (Exception ex)
            {
                return BadRequest(AdministrarExcepcion(ex));
            }
        }

        /// <summary>
        /// Realiza la migración masiva de usuarios
        /// </summary>
        /// <remarks>Procesa la migración masiva de usuarios que ya se hayan cargado en la base de datos. </remarks>
        /// <param name="usuario">Identificación del usuario que inicia el proceso</param>
        /// <response code="200">Resultado de la migración masiva</response>
        /// <response code="400">Error en la petición</response>
        [HttpPost]
        [Route("migraciones/{usuario}/masiva")]
        [ValidateModelState]
        [SwaggerOperation("RealizarMigracionMasiva")]
        [SwaggerResponse(statusCode: 200, type: typeof(RespuestaTransaccion), description: "Resultado de la migración masiva")]
        [SwaggerResponse(statusCode: 400, type: typeof(MensajeErrorItem), description: "Error en la petición")]
        public virtual async Task<IActionResult> RealizarMigracionMasiva([FromRoute][Required] string usuario)
        {
            try
            {
                ProcesoBL reglasNegocio = new ProcesoBL(_context);
                RespuestaTransaccion respuesta = await reglasNegocio.RealizarMigracionMasiva(usuario, _serviceProvider);
                respuesta.Url = new Uri(Request.GetDisplayUrl()).ToString();
                return new ObjectResult(respuesta);
            }
            catch (Exception ex)
            {
                return BadRequest(AdministrarExcepcion(ex));
            }
        }
    }
}
